/**
 * The vocabulary of הנהח״ש.
 *
 * Bookkeeping terms are their own language — כרטסת, מאזן בוחן, אסמכתא, חובה,
 * זכות — and they belong together rather than scattered through the app-wide
 * dictionary. Hebrew is the primary; English is what an English-locale viewer
 * gets, translated as a bookkeeper would say it, not word-for-word.
 */

export const BOOKS_STRINGS = {
  he: {
    section: 'הנהח״ש',
    overview: 'סקירה',
    accounts: 'אינדקס הנהח״ש',
    ledgerCard: 'כרטסת',
    trialBalance: 'מאזן בוחן',
    journal: 'פקודות יומן',
    vat: 'מע״מ',
    cash: 'קופה',
    purchasing: 'רכש',
    years: 'שנים',
    suppliers: 'יתרות ספקים',
    banks: 'דפי בנק',
    cheques: 'שיקים',
    payments: 'תשלומים',
    orders: 'הוראות תשלום',

    account: 'חשבון',
    accountName: 'שם',
    balanceCode: 'מאזן',
    city: 'עיר',
    taxId: 'ח.פ',
    movements: 'תנועות',
    debit: 'חובה',
    credit: 'זכות',
    balance: 'יתרה',
    date: 'תאריך',
    dueDate: 'לפרעון',
    payDate: 'ת. פרעון',
    valueDate: 'ת. ערך',
    reference: 'אסמכתא',
    detail: 'פרטים',
    counterAccount: 'חשבון נגדי',
    lines: 'שורות',
    docType: 'סוג',
    entryNumber: 'פקודה',
    balanced: 'מאוזן',
    opening: 'יתרת פתיחה',
    total: 'סה״כ',

    receipt: 'קבלה',
    receiptNumber: 'מספר קבלה',
    tender: 'אמצעי',
    bank: 'בנק',
    branch: 'סניף',
    depositAccount: 'חשבון הפקדה',
    time: 'שעה',
    amount: 'סכום',
    page: 'דף',
    supplier: 'ספק',
    lastMovement: 'תנועה אחרונה',

    turnover: 'מחזור חייב',
    vatOut: 'מע״מ עסקאות',
    vatIn: 'מע״מ תשומות',
    vatDue: 'מע״מ לתשלום',
    sales: 'מכירות',
    purchases: 'רכש',
    receipts: 'תקבולים',
    debtors: 'חייבים',
    creditors: 'זכאים',
    booksBalance: 'איזון הספרים',
    inBalance: 'מאוזן',

    from: 'מתאריך',
    to: 'עד',
    search: 'חיפוש',
    filter: 'סינון',
    clear: 'נקה',
    export: 'ייצוא',
    includeZero: 'כולל יתרות אפס',
    allTypes: 'כל הסוגים',
    allAccounts: 'כל סוגי החשבונות',
    month: 'חודש',
    year: 'שנה',
    live: 'חי',
    closedYear: 'שנה סגורה',
    refresh: 'רענון',
    refreshed: 'עודכן',
    staleWarning: 'הנתונים לא התעדכנו מה-ERP בשעות האחרונות',
    openInDashboard: 'פתיחה בדשבורד',
    noRows: 'אין נתונים בטווח הזה',
    noRowsHint: 'נסה טווח תאריכים אחר או נקה את הסינון',
    showing: 'מוצגות',
    of: 'מתוך',
    prev: 'הקודם',
    next: 'הבא',

    aiTitle: 'ניתוח AI',
    aiHint: 'קורא את נתוני התקופה וכותב מה הם אומרים',
    aiRun: 'נתח את הספרים',
    aiRunning: 'קורא את הספרים…',
    aiAgain: 'נתח שוב',
    aiSaved: 'תשובה שמורה (עד שבוע)',

    monthlyFlow: 'מכירות, רכש ותקבולים',
    monthlyFlowHint: 'הכל בשקלים, סקאלה אחת',
    vatChart: 'עסקאות מול תשומות, והחוב שנוצר',
    balanceTrend: 'מהלך היתרה',
    cashMix: 'תקבולים לפי חודש',
    chequeTimeline: 'שיקים לפרעון',
    postedToBooks: 'הרישום בספרים',
    vatMovements: 'תנועות מע״מ',
    biggestBalances: 'היתרות הגדולות בטווח',
    range3m: '3 חודשים',
    range6m: '6 חודשים',
    rangeYear: 'שנה',
    rangeAll: 'הכל',
  },
  en: {
    section: 'Bookkeeping',
    overview: 'Overview',
    accounts: 'Chart of accounts',
    ledgerCard: 'Ledger card',
    trialBalance: 'Trial balance',
    journal: 'Journal',
    vat: 'VAT',
    cash: 'Cash',
    purchasing: 'Purchasing',
    years: 'Years',
    suppliers: 'Supplier balances',
    banks: 'Bank statements',
    cheques: 'Cheques',
    payments: 'Payments',
    orders: 'Payment orders',

    account: 'Account',
    accountName: 'Name',
    balanceCode: 'Class',
    city: 'City',
    taxId: 'Tax ID',
    movements: 'Movements',
    debit: 'Debit',
    credit: 'Credit',
    balance: 'Balance',
    date: 'Date',
    dueDate: 'Due',
    payDate: 'Pay date',
    valueDate: 'Value date',
    reference: 'Reference',
    detail: 'Detail',
    counterAccount: 'Counter account',
    lines: 'Lines',
    docType: 'Type',
    entryNumber: 'Entry',
    balanced: 'Balanced',
    opening: 'Opening balance',
    total: 'Total',

    receipt: 'Receipt',
    receiptNumber: 'Receipt no.',
    tender: 'Tender',
    bank: 'Bank',
    branch: 'Branch',
    depositAccount: 'Deposit account',
    time: 'Time',
    amount: 'Amount',
    page: 'Page',
    supplier: 'Supplier',
    lastMovement: 'Last movement',

    turnover: 'Taxable turnover',
    vatOut: 'Output VAT',
    vatIn: 'Input VAT',
    vatDue: 'VAT payable',
    sales: 'Sales',
    purchases: 'Purchases',
    receipts: 'Receipts',
    debtors: 'Debtors',
    creditors: 'Creditors',
    booksBalance: 'Books balance',
    inBalance: 'In balance',

    from: 'From',
    to: 'To',
    search: 'Search',
    filter: 'Filter',
    clear: 'Clear',
    export: 'Export',
    includeZero: 'Include zero balances',
    allTypes: 'All types',
    allAccounts: 'All account types',
    month: 'Month',
    year: 'Year',
    live: 'Live',
    closedYear: 'Closed year',
    refresh: 'Refresh',
    refreshed: 'Updated',
    staleWarning: 'These figures have not been refreshed from the ERP for hours',
    openInDashboard: 'Open in dashboard',
    noRows: 'Nothing in this range',
    noRowsHint: 'Try another date range, or clear the filter',
    showing: 'Showing',
    of: 'of',
    prev: 'Previous',
    next: 'Next',

    aiTitle: 'AI analysis',
    aiHint: 'Reads the period and writes what it says',
    aiRun: 'Analyse the books',
    aiRunning: 'Reading the books…',
    aiAgain: 'Analyse again',
    aiSaved: 'saved answer (kept a week)',

    monthlyFlow: 'Sales, purchases and receipts',
    monthlyFlowHint: 'One shekel scale',
    vatChart: 'Output vs input VAT, and what it leaves owing',
    balanceTrend: 'Balance over time',
    cashMix: 'Receipts by month',
    chequeTimeline: 'Cheques falling due',
    postedToBooks: 'Posted to the books',
    vatMovements: 'VAT movements',
    biggestBalances: 'Largest balances in range',
    range3m: '3 months',
    range6m: '6 months',
    rangeYear: 'Year',
    rangeAll: 'All',
  },
} as const

export type BooksStringKey = keyof typeof BOOKS_STRINGS.he

/** Document kinds, keyed by the reference prefix the ERP writes. */
export const DOC_TYPES: Record<string, { he: string; en: string }> = {
  D11: { he: 'חשבונית מס', en: 'Tax invoice' },
  D12: { he: 'חשבונית זיכוי', en: 'Credit note' },
  D13: { he: 'חשבונית מרכזת', en: 'Consolidated invoice' },
  D19: { he: 'חשבונית מס קבלה', en: 'Invoice + receipt' },
  D21: { he: 'תעודת משלוח', en: 'Delivery note' },
  D31: { he: 'הצעת מחיר', en: 'Quote' },
  D51: { he: 'חשבונית מספק בארץ', en: 'Domestic supplier invoice' },
  D52: { he: 'חשבונית יבוא', en: 'Import invoice' },
  D53: { he: 'ת. משלוח מספק', en: 'Supplier delivery note' },
  D58: { he: 'חשבונית מספק חו״ל', en: 'Foreign supplier invoice' },
  D59: { he: 'קליטת יבוא', en: 'Import receipt' },
  D61: { he: 'הזמנה מספק', en: 'Supplier order' },
  D62: { he: 'הזמנה בדרך', en: 'In-transit order' },
  K01: { he: 'קבלה', en: 'Receipt' },
  K19: { he: 'קבלה על חשבונית', en: 'Receipt on invoice' },
  Y00: { he: 'פקודת יומן', en: 'Journal entry' },
  Y11: { he: 'פקודה — חשבונית', en: 'Entry — invoice' },
  Y12: { he: 'פקודה — זיכוי', en: 'Entry — credit' },
  Y13: { he: 'פקודה — מרכזת', en: 'Entry — consolidated' },
  H01: { he: 'תנועת בנק', en: 'Bank movement' },
  C00: { he: 'שיק / הוראת תשלום', en: 'Cheque / payment order' },
}

/** Receipt tender codes, as the ERP writes them on a payment line. */
export const PAY_TYPES: Record<string, { he: string; en: string }> = {
  '01': { he: 'שיק', en: 'Cheque' },
  '02': { he: 'מזומן', en: 'Cash' },
  '03': { he: 'העברה', en: 'Transfer' },
  '04': { he: 'העברה בנקאית', en: 'Bank transfer' },
  '10': { he: 'העברה', en: 'Transfer' },
  '11': { he: 'העברה', en: 'Transfer' },
  '20': { he: 'כרטיס אשראי', en: 'Credit card' },
  '21': { he: 'כרטיס אשראי', en: 'Credit card' },
  '22': { he: 'כרטיס אשראי', en: 'Credit card' },
  '30': { he: 'שיק דחוי', en: 'Deferred cheque' },
  '31': { he: 'שיק דחוי', en: 'Deferred cheque' },
  '40': { he: 'קיזוז', en: 'Offset' },
  '41': { he: 'קיזוז', en: 'Offset' },
}

/** Account classes as the ERP codes them (קוד מאזן). */
export const ACCOUNT_CLASSES: Record<string, { he: string; en: string }> = {
  '2111': { he: 'לקוחות', en: 'Customers' },
  '2114': { he: 'לקוחות', en: 'Customers' },
  '2122': { he: 'לקוחות', en: 'Customers' },
  '431': { he: 'ספקים', en: 'Suppliers' },
  '432': { he: 'ספקים', en: 'Suppliers' },
  '40': { he: 'הוצאות', en: 'Expenses' },
  '42': { he: 'הוצאות', en: 'Expenses' },
  '44': { he: 'הוצאות', en: 'Expenses' },
  '45': { he: 'הוצאות', en: 'Expenses' },
  '46': { he: 'הוצאות', en: 'Expenses' },
  '48': { he: 'הוצאות', en: 'Expenses' },
  '81': { he: 'הכנסות', en: 'Revenue' },
  '85': { he: 'הכנסות', en: 'Revenue' },
  '91': { he: 'מאזן', en: 'Balance sheet' },
}
